/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dunnsform;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
/**
 *
 * @author Hillary Kahari
 */
public class ProductDescription extends javax.swing.JFrame {
    private String strline;

    /**
     * Creates new form ProductDescription
     */
    public ProductDescription() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstList = new javax.swing.JList();
        btnCreatethefilefordescription = new javax.swing.JButton();
        btnClearitems = new javax.swing.JButton();
        txtInput = new javax.swing.JTextField();
        lblOutput = new javax.swing.JLabel();
        btnAddDescription = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setForeground(new java.awt.Color(0, 0, 0));
        btnBack.setText("Go back to inventory");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lstList.setBackground(new java.awt.Color(204, 204, 255));
        lstList.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(lstList);

        btnCreatethefilefordescription.setBackground(new java.awt.Color(0, 102, 102));
        btnCreatethefilefordescription.setForeground(new java.awt.Color(0, 0, 0));
        btnCreatethefilefordescription.setText("Create the file for Description");
        btnCreatethefilefordescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreatethefilefordescriptionMouseClicked(evt);
            }
        });
        btnCreatethefilefordescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatethefilefordescriptionCreatethefilefordescriptionActionPerformed(evt);
            }
        });

        btnClearitems.setBackground(new java.awt.Color(0, 102, 102));
        btnClearitems.setForeground(new java.awt.Color(0, 0, 0));
        btnClearitems.setText("Clear items");
        btnClearitems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearitemsActionPerformed(evt);
            }
        });

        txtInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputActionPerformed(evt);
            }
        });

        btnAddDescription.setBackground(new java.awt.Color(0, 102, 102));
        btnAddDescription.setForeground(new java.awt.Color(0, 0, 0));
        btnAddDescription.setText("Add Description");
        btnAddDescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddDescriptionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddDescriptionMouseEntered(evt);
            }
        });
        btnAddDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDescriptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(438, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtInput)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCreatethefilefordescription, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClearitems, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddDescription)
                        .addGap(65, 65, 65)
                        .addComponent(lblOutput)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnBack)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClearitems, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(btnCreatethefilefordescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOutput)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    MyOrderScreen myOrderScreen = new MyOrderScreen();
    myOrderScreen.show();
    myOrderScreen.setSize(1400,700);
    myOrderScreen.setResizable(false);
    this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed
    DefaultListModel<String> dlmList = new DefaultListModel<>();
    private void btnCreatethefilefordescriptionCreatethefilefordescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatethefilefordescriptionCreatethefilefordescriptionActionPerformed
    dlmList.addElement(txtInput.getText());
        lstList.setModel(dlmList);
        txtInput.setText("");
        txtInput.requestFocusInWindow(); // TODO add your handling code here:
    }//GEN-LAST:event_btnCreatethefilefordescriptionCreatethefilefordescriptionActionPerformed

    private void btnClearitemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearitemsActionPerformed
    dlmList.removeAllElements();        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearitemsActionPerformed

    private void btnCreatethefilefordescriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreatethefilefordescriptionMouseClicked
                // TODO add your handling code here:
    }//GEN-LAST:event_btnCreatethefilefordescriptionMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
    MyOrderScreen myOrderScreen = new MyOrderScreen();
        myOrderScreen.show();
        myOrderScreen.setSize(1400, 700);
        myOrderScreen.setResizable(false);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackMouseClicked

    private void txtInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputActionPerformed

    private void btnAddDescriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddDescriptionMouseClicked
                // TODO add your handling code here:
    }//GEN-LAST:event_btnAddDescriptionMouseClicked

    private void btnAddDescriptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddDescriptionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddDescriptionMouseEntered

    private void btnAddDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDescriptionActionPerformed

        int intIndex = lstList.getModel().getSize();
        String[] arrSTR = new String[intIndex];

        for(int i = 0; i <intIndex; i++)
        {
            arrSTR[i]= (String) lstList.getModel().getElementAt(i);

            try
            {
                String strfilename= "textfile.txt";
                try (FileWriter fw = new FileWriter(strfilename,true)) {
                    fw.write(arrSTR[i]+ "");
                }
                lblOutput.setText("content has been written to the file");
            }
            catch (Exception Ex)
            {
                JOptionPane.showMessageDialog(null, Ex);

            }

        }// TODO add your handling code here:
    }//GEN-LAST:event_btnAddDescriptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductDescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductDescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductDescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductDescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ProductDescription().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDescription;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClearitems;
    private javax.swing.JButton btnCreatethefilefordescription;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JList lstList;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
